version: '3'

services:
  api:
    build: 
      context: .
    image: rafaelps1/brq-app
    container_name: api
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - bqr-net
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - bqr-net

networks:
  bqr-net:
    driver: bridge
