version: '3'

services:
  app:
    build: 
      context: .
    image: rafaelps1/brq-app
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - bqrnet

networks:
  bqrnet:
    driver: bridge
